# -*- coding: utf-8 -*-
"""Untitled33.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cAH_RlWz0Xk26ImrKKWllxqSLKSXcMEm
"""

!pip -q install pandas numpy scikit-learn matplotlib seaborn kagglehub ucimlrepo

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.ensemble import IsolationForest
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.metrics import (
    precision_score, recall_score, f1_score,
    accuracy_score, confusion_matrix, classification_report
)

print("Libraries installed and imported successfully.")

import requests
import json

record_id = "8136017"
api_url = f"https://zenodo.org/api/records/{record_id}"

r = requests.get(api_url)
r.raise_for_status()

record = r.json()

print("Title:", record["metadata"]["title"])
print("\nFiles available:")
for f in record["files"]:
    print("-", f["key"], "|", f["links"]["self"])

import requests

data_url = "https://zenodo.org/api/records/8136017/files/data.zip/content"

resp = requests.get(data_url)
resp.raise_for_status()

with open("data.zip", "wb") as f:
    f.write(resp.content)

print("Downloaded data.zip")

import zipfile
import os

with zipfile.ZipFile("data.zip", "r") as z:
    z.extractall("uci_shell_data")

print("Extracted files:")
print(os.listdir("uci_shell_data"))

import os
import json
import pandas as pd

base_dir = "uci_shell_data"

scenario_dirs = [
    "SQL injection",
    "Junior hacker",
    "Secret laboratory",
    "Junior hacker adaptive",
    "House of cards",
    "Webmin exploit practice",
    "Locust 3302",
]

all_records = []

for scen in scenario_dirs:
    scen_path = os.path.join(base_dir, scen)
    if not os.path.isdir(scen_path):
        print("Skipping (not a directory):", scen_path)
        continue

    for fname in os.listdir(scen_path):
        if not fname.lower().endswith(".json"):
            continue
        fpath = os.path.join(scen_path, fname)
        with open(fpath, "r") as f:
            # Each file is JSON Lines: one JSON object per line
            for line in f:
                line = line.strip()
                if not line:
                    continue
                try:
                    rec = json.loads(line)
                    rec["scenario"] = scen  # keep track of scenario name
                    all_records.append(rec)
                except json.JSONDecodeError:
                    # skip malformed lines if any
                    continue

print(f"Total records loaded from all scenarios: {len(all_records)}")

uci_df = pd.DataFrame(all_records)
print("UCI shell commands DataFrame shape:", uci_df.shape)
uci_df.head()

from sklearn.preprocessing import LabelEncoder
import pandas as pd

uci_fe = uci_df.copy()

# 1) Parse timestamp safely with UTC
uci_fe["timestamp"] = pd.to_datetime(uci_fe["timestamp_str"], errors="coerce", utc=True)

uci_fe["hour"] = uci_fe["timestamp"].dt.hour.fillna(-1).astype(int)
uci_fe["day_of_week"] = uci_fe["timestamp"].dt.dayofweek.fillna(-1).astype(int)
uci_fe["is_night"] = ((uci_fe["hour"] < 6) | (uci_fe["hour"] > 22)).astype(int)

# 2) Command-based features
uci_fe["cmd"] = uci_fe["cmd"].astype(str)
uci_fe["command_length"] = uci_fe["cmd"].str.len()
uci_fe["special_chars"] = uci_fe["cmd"].str.count(r"[|&;><$`]")

uci_fe["has_sudo"] = uci_fe["cmd"].str.contains(r"sudo|root", case=False, na=False).astype(int)
uci_fe["has_network"] = uci_fe["cmd"].str.contains(r"nc |nmap|wget |curl |ssh ", case=False, na=False).astype(int)
uci_fe["has_delete"] = uci_fe["cmd"].str.contains(r"\brm\b", case=False, na=False).astype(int)
uci_fe["has_passwd"] = uci_fe["cmd"].str.contains(r"passwd", case=False, na=False).astype(int)
uci_fe["has_sql"] = uci_fe["cmd"].str.contains(r"sqlmap|mysql|psql", case=False, na=False).astype(int)

# 3) Encode categorical columns
categorical_cols = ["hostname", "username", "ip", "wd", "cmd_type", "scenario"]
encoders = {}

for col in categorical_cols:
    if col in uci_fe.columns:
        le = LabelEncoder()
        uci_fe[f"{col}_enc"] = le.fit_transform(uci_fe[col].astype(str))
        encoders[col] = le

print("Engineered columns created successfully.")
print(uci_fe[[
    "cmd", "timestamp", "hour", "day_of_week", "is_night",
    "command_length", "special_chars",
    "has_sudo", "has_network", "has_delete", "has_passwd", "has_sql"
]].head())

feature_cols_uci = [
    "hour", "day_of_week", "is_night",
    "command_length", "special_chars",
    "has_sudo", "has_network", "has_delete", "has_passwd", "has_sql",
    "hostname_enc", "username_enc", "ip_enc", "wd_enc", "cmd_type_enc", "scenario_enc"
]

X_uci = uci_fe[feature_cols_uci].fillna(uci_fe[feature_cols_uci].median())
print("Feature matrix shape:", X_uci.shape)

from sklearn.ensemble import IsolationForest
from sklearn.preprocessing import StandardScaler

# Scale features (good practice for tree ensembles on mixed-scale data)
scaler_uci = StandardScaler()
X_uci_scaled = scaler_uci.fit_transform(X_uci)

# Train Isolation Forest (unsupervised)
iso_uci = IsolationForest(
    contamination=0.05,   # expect ~5% anomalies; you can tune this later
    n_estimators=200,
    random_state=42,
    n_jobs=-1
)
iso_uci.fit(X_uci_scaled)

# Get scores and anomaly labels
uci_fe["anomaly_score"] = iso_uci.decision_function(X_uci_scaled)
uci_fe["is_anomaly"] = (iso_uci.predict(X_uci_scaled) == -1).astype(int)

total = len(uci_fe)
anoms = uci_fe["is_anomaly"].sum()
print(f"Total commands: {total}")
print(f"Anomalies detected: {anoms} ({anoms/total:.2%})")

uci_fe[["cmd", "scenario", "hour", "is_night", "anomaly_score", "is_anomaly"]].head()

def llm_risk_classify(command: str) -> str:
    """
    Simulated LLM risk classifier.
    Returns: 'Critical', 'High', 'Medium', or 'Low'.
    """
    cmd = command.lower()

    # Critical risk - immediate session termination
    critical_patterns = [
        "sudo su", "passwd root", "chmod 777 /etc/shadow",
        "rm -rf /", "aws iam create-access-key",
        "nc -lvp", "nc -lvnp", "wget http://", "wget https://",
        "curl http://", "curl https://", "ssh -i", "ssh root@"
    ]

    # High risk - SOC alert
    high_patterns = [
        "cat /etc/shadow", "cat /etc/passwd", "ssh-copy-id",
        "scp ", "tar czf", "base64 ", "sqlmap", "nmap", "hydra "
    ]

    # Medium risk - log only
    medium_patterns = [
        "systemctl stop", "iptables -f", "iptables - flush",
        "useradd ", "usermod ", "chown ", "chmod 777 ",
        "mysql ", "psql "
    ]

    if any(p in cmd for p in critical_patterns):
        return "Critical"
    elif any(p in cmd for p in high_patterns):
        return "High"
    elif any(p in cmd for p in medium_patterns):
        return "Medium"
    else:
        return "Low"

# Filter to anomalies only
uci_anoms = uci_fe[uci_fe["is_anomaly"] == 1].copy()
print("Anomalous commands:", len(uci_anoms))

# Apply simulated LLM risk classification
uci_anoms["llm_risk"] = uci_anoms["cmd"].apply(llm_risk_classify)

# Risk distribution
risk_counts = uci_anoms["llm_risk"].value_counts().sort_index()
risk_percent = (risk_counts / len(uci_anoms) * 100).round(2)

print("\nRisk counts:")
print(risk_counts)
print("\nRisk percentages (%):")
print(risk_percent)

# Define a pseudo-session ID
uci_anoms["session_id"] = uci_anoms["ip"].astype(str) + "_" + uci_anoms["username"].astype(str)

critical_cmds = uci_anoms[uci_anoms["llm_risk"] == "Critical"]
critical_sessions = critical_cmds["session_id"].unique()

print("Critical commands:", len(critical_cmds))
print("Sessions to terminate:", len(critical_sessions))

critical_cmds[[
    "cmd", "scenario", "hostname", "username", "ip",
    "session_id", "hour", "is_night", "anomaly_score", "llm_risk"
]].head(20)

import matplotlib.pyplot as plt
import seaborn as sns

sns.set(style="whitegrid")

# Map 0/1 to labels
class_counts = uci_fe["is_anomaly"].map({0: "Normal", 1: "Anomaly"}).value_counts()

plt.figure(figsize=(5,4))
sns.barplot(
    x=class_counts.index,
    y=class_counts.values,
    palette=["#2ecc71", "#e74c3c"]
)
plt.title("Anomaly Detection Results (UCI Shell Commands)")
plt.xlabel("Class")
plt.ylabel("Number of Commands")
plt.tight_layout()
plt.savefig("uci_anomaly_results.png", dpi=300)
plt.show()

print("Saved figure: uci_anomaly_results.png")

plt.figure(figsize=(5,4))
order = ["Critical", "High", "Medium", "Low"]
sns.countplot(
    data=uci_anoms,
    x="llm_risk",
    order=order,
    palette=["#c0392b", "#e67e22", "#f1c40f", "#27ae60"]
)
plt.title("LLM Risk Classification for Anomalous Commands (UCI)")
plt.xlabel("Risk Level")
plt.ylabel("Number of Commands")
plt.tight_layout()
plt.savefig("uci_llm_risk_distribution.png", dpi=300)
plt.show()

print("Saved figure: uci_llm_risk_distribution.png")

# Group by hour and compute anomaly rate
hourly = uci_fe.groupby("hour")["is_anomaly"].mean() * 100

plt.figure(figsize=(8,4))
hourly.plot(kind="bar", color="#3498db")
plt.title("Anomaly Rate by Hour of Day (UCI)")
plt.xlabel("Hour of Day")
plt.ylabel("Anomaly Rate (%)")
plt.tight_layout()
plt.savefig("uci_anomaly_rate_by_hour.png", dpi=300)
plt.show()

print("Saved figure: uci_anomaly_rate_by_hour.png")

!pip -q install kagglehub

import kagglehub

# This will download the SSH anomaly dataset into a local path
ssh_path = kagglehub.dataset_download("mdwiraputradananjaya/ssh-anomaly-dataset")
print("Dataset downloaded to:", ssh_path)

import os

print("Files in dataset folder:")
for root, dirs, files in os.walk(ssh_path):
    for f in files:
        print(os.path.join(root, f))

import pandas as pd
import os

ssh_csv_path = os.path.join(ssh_path, "ssh_anomaly_dataset.csv")
ssh_df = pd.read_csv(ssh_csv_path)

print("SSH dataset shape:", ssh_df.shape)
ssh_df.head()

print("Columns:", ssh_df.columns.tolist())
print("\nInfo:")
print(ssh_df.info())

from sklearn.preprocessing import LabelEncoder

ssh_fe = ssh_df.copy()

# 1) Parse timestamp
ssh_fe["timestamp"] = pd.to_datetime(ssh_fe["timestamp"], errors="coerce", utc=True)
ssh_fe["hour"] = ssh_fe["timestamp"].dt.hour.fillna(-1).astype(int)
ssh_fe["day_of_week"] = ssh_fe["timestamp"].dt.dayofweek.fillna(-1).astype(int)
ssh_fe["is_night"] = ((ssh_fe["hour"] < 6) | (ssh_fe["hour"] > 22)).astype(int)

# 2) Event-type and status flags (command-like vs authentication vs disconnect)
ssh_fe["is_command_event"] = ssh_fe["event_type"].str.contains("Command", case=False, na=False).astype(int)
ssh_fe["is_auth_event"]    = ssh_fe["event_type"].str.contains("Accepted|Failed|Login", case=False, na=False).astype(int)
ssh_fe["is_disconnect"]    = ssh_fe["event_type"].str.contains("Disconnected|logout", case=False, na=False).astype(int)

# 3) Label encode categorical columns
categorical_cols_ssh = ["source_ip", "username", "event_type", "status"]
encoders_ssh = {}

for col in categorical_cols_ssh:
    if col in ssh_fe.columns:
        le = LabelEncoder()
        ssh_fe[f"{col}_enc"] = le.fit_transform(ssh_fe[col].astype(str))
        encoders_ssh[col] = le

# 4) Binary label: 0=normal, 1=attack
ssh_fe["label_bin"] = (ssh_fe["label"].str.lower() != "normal").astype(int)

print("Feature engineering complete.")
ssh_fe[[
    "timestamp", "source_ip", "username",
    "event_type", "status", "label", "label_bin",
    "hour", "day_of_week", "is_night",
    "is_command_event", "is_auth_event", "is_disconnect"
]].head()

feature_cols_ssh = [
    "hour", "day_of_week", "is_night",
    "is_command_event", "is_auth_event", "is_disconnect",
    "source_ip_enc", "username_enc", "event_type_enc", "status_enc"
]

X_ssh = ssh_fe[feature_cols_ssh].fillna(ssh_fe[feature_cols_ssh].median())
y_ssh = ssh_fe["label_bin"]

print("X_ssh shape:", X_ssh.shape)
print("Number of attacks (label=1):", y_ssh.sum())

from sklearn.ensemble import IsolationForest
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import (
    precision_score, recall_score, f1_score,
    accuracy_score, confusion_matrix, classification_report
)

# Scale features
scaler_ssh = StandardScaler()
X_ssh_scaled = scaler_ssh.fit_transform(X_ssh)

# Train Isolation Forest (unsupervised)
iso_ssh = IsolationForest(
    contamination=0.05,    # target ~5% anomalies; you can tune this
    n_estimators=200,
    random_state=42,
    n_jobs=-1
)
iso_ssh.fit(X_ssh_scaled)

# Predictions
ssh_fe["anomaly_score"] = iso_ssh.decision_function(X_ssh_scaled)
ssh_fe["is_anomaly"] = (iso_ssh.predict(X_ssh_scaled) == -1).astype(int)

print("Total events:", len(ssh_fe))
print("Anomalies detected:", ssh_fe["is_anomaly"].sum(),
      f"({ssh_fe['is_anomaly'].mean()*100:.2f}%)")

y_true = y_ssh          # 0=normal, 1=attack
y_pred = ssh_fe["is_anomaly"]  # 0=pred normal, 1=pred anomaly

precision = precision_score(y_true, y_pred, zero_division=0)
recall = recall_score(y_true, y_pred, zero_division=0)
f1 = f1_score(y_true, y_pred, zero_division=0)
acc = accuracy_score(y_true, y_pred)

cm = confusion_matrix(y_true, y_pred)

print("Confusion matrix [[TN, FP],[FN, TP]]:\n", cm)
print(f"\nPrecision: {precision:.3f}")
print(f"Recall:    {recall:.3f}")
print(f"F1-score:  {f1:.3f}")
print(f"Accuracy:  {acc:.3f}")

print("\nClassification report:\n", classification_report(y_true, y_pred, zero_division=0))

from sklearn.svm import OneClassSVM
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import (
    precision_score, recall_score, f1_score,
    accuracy_score, confusion_matrix, classification_report
)

# Use the same engineered SSH dataframe: ssh_fe
# label_bin: 0 = normal, 1 = attack

# Training set: only normal events
train_normal = ssh_fe[ssh_fe["label_bin"] == 0].copy()

# Test set: full dataset
test_all = ssh_fe.copy()

# Feature columns from before
feature_cols_ssh = [
    "hour", "day_of_week", "is_night",
    "is_command_event", "is_auth_event", "is_disconnect",
    "source_ip_enc", "username_enc", "event_type_enc", "status_enc"
]

X_train = train_normal[feature_cols_ssh].fillna(train_normal[feature_cols_ssh].median())
X_test = test_all[feature_cols_ssh].fillna(test_all[feature_cols_ssh].median())

y_test = test_all["label_bin"]   # 0=normal, 1=attack

print("Training normals:", len(X_train))
print("Testing rows:", len(X_test))
print("Testing attacks:", y_test.sum())

scaler_ocsvm = StandardScaler()
X_train_scaled = scaler_ocsvm.fit_transform(X_train)
X_test_scaled = scaler_ocsvm.transform(X_test)

ocsvm = OneClassSVM(
    kernel="rbf",
    gamma="scale",
    nu=0.05   # expected fraction of outliers relative to normal profile
)

ocsvm.fit(X_train_scaled)

ocsvm_pred = ocsvm.predict(X_test_scaled)
test_all["ocsvm_is_anomaly"] = (ocsvm_pred == -1).astype(int)

y_true = y_test
y_pred = test_all["ocsvm_is_anomaly"]

precision = precision_score(y_true, y_pred, zero_division=0)
recall = recall_score(y_true, y_pred, zero_division=0)
f1 = f1_score(y_true, y_pred, zero_division=0)
acc = accuracy_score(y_true, y_pred)
cm = confusion_matrix(y_true, y_pred)

print("Confusion matrix [[TN, FP],[FN, TP]]:\n", cm)
print(f"\nPrecision: {precision:.3f}")
print(f"Recall:    {recall:.3f}")
print(f"F1-score:  {f1:.3f}")
print(f"Accuracy:  {acc:.3f}")

print("\nClassification report:\n", classification_report(y_true, y_pred, zero_division=0))



